name: Helm Chart Testing and Artifact Build

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main
      - develop
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.13.0' # You can specify the Helm version you want to use

    - name: Install Helm Chart Dependencies
      run: |
        helm dependency update

    - name: Lint Helm Chart
      run: |
        helm lint .

    - name: Package Chart
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        helm package -d chart .
        mv chart/kobo*.tgz chart/kobo.tgz 

  dry-run:
    needs: build-and-publish
    runs-on: ubuntu-latest

    steps:
    - name: Install Kind
      run: |
        curl -Lo kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
        chmod +x kind
        sudo mv kind /usr/local/bin/

    - name: Create Kind Cluster
      run: kind create cluster --name my-kind-cluster

    - name: Create Custom my-values.yaml
      run: |
        echo "customKey1: customValue1" > my-values.yaml
        echo "customKey2: customValue2" >> my-values.yaml
        # Add more custom values as needed

    - name: Deploy Helm Chart to Kind
      run: |
        cd chart
        helm upgrade --install kobo . --namespace default --wait